project_name: 'pwa-server'

builds:
  - main: './cmd/pwa-server/main.go'
    goos: ['linux', 'darwin', 'windows']
    goarch: ['386', 'amd64', 'arm', 'arm64']
    goarm: ['6', '7']
    env:
      - CGO_ENABLED=0

changelog:
  sort: 'asc'
  filters:
    exclude: ['^docs:', '^test:', 'Merge pull request', 'Merge branch']

archives:
  - format_overrides:
    - goos: 'windows'
      format: 'zip'
    wrap_in_directory: true
    files:
      - README.md

nfpms:
  - homepage: 'https://github.com/brunoluiz/pwa-server'
    description: '🚀 Fast static server for your PWA applications'
    maintainer: 'Bruno Silva <contact@brunoluiz.net>'
    formats: ['deb', 'rpm']
    dependencies: ['git']

dockers:
  - image_templates:
    - 'brunoluiz/pwa-server:{{ .Tag }}'
    - 'brunoluiz/pwa-server:v{{ .Major }}.{{ .Minor }}'
    - 'brunoluiz/pwa-server:latest'
    dockerfile: 'Dockerfile.prod'

brews:
  - github:
      owner: 'brunoluiz'
      name: 'homebrew-tap'
    folder: 'Formula'
    homepage: 'https://github.com/brunoluiz/pwa-server'
    description: '🚀 Fast static server for your PWA applications'
